# Overview: build and create a release via Google Cloud Deploy for GKE
# NOTE: currently requires SCM triggering due to dependency on the COMMIT_SHA variable
# Update these values, if desired
steps:
  - name: maven:3-eclipse-temurin
    entrypoint: mvn
    args: ['test']
  # build app with Maven
  - name: maven:3-eclipse-temurin-17
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
  - name: gcr.io/cloud-builders/mvn
    entrypoint: mvn
    args: ["deploy"]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: /bin/sh
    args:
    - '-c'
    - |
      # copy files to destination
      mv target/hello-world-*.war target/hello-world.war
      gcloud compute scp --zone ${_ZONE} target/hello-world.war cloudbuild@${_INSTANCE_NAME}:/var/lib/tomcat9/webapps/hello-world.war --tunnel-through-iap
      gcloud compute ssh ${_INSTANCE_NAME} --tunnel-through-iap --zone ${_ZONE} --command 'sudo service tomcat9 restart'
substitutions:
  _ZONE: asia-south1-c # default value
  _INSTANCE_NAME: cicd-demo-vm # default value
